apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event-bus-service
  template:
    metadata:
      labels:
        app: event-bus-service
    spec:
      containers:
      - name: event-bus-service
        image: killua214/event-bus-service:latest
        ports:
        - containerPort: 4001